/* automatically generated from xfce4-session-settings.ui */
#ifdef __SUNPRO_C
#pragma align 4 (xfce4_session_settings_ui)
#endif
#ifdef __GNUC__
static const char xfce4_session_settings_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfce4_session_settings_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.12\"/><requires lib=\"libxfce4ui-2\" version=\"4.12\"/"
  "><object class=\"GtkImage\" id=\"image1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"icon_name\">edit-clear-symbolic</property></object><object class=\""
  "GtkImage\" id=\"image2\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"icon_name\">d"
  "ocument-save-symbolic</property></object><object class=\"GtkImage\" id="
  "\"image3\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"icon_name\">list-remove-sym"
  "bolic</property></object><object class=\"GtkImage\" id=\"image4\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"icon_name\">list-remove-symbolic</property>"
  "</object><object class=\"GtkImage\" id=\"image5\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"icon_name\">window-close-symbolic</property></object><objec"
  "t class=\"GtkImage\" id=\"image7\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"ico"
  "n_name\">help-browser</property></object><object class=\"GtkImage\" id="
  "\"image8\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"icon_name\">help-browser</p"
  "roperty></object><object class=\"GtkPopover\" id=\"session-info\"><prop"
  "erty name=\"can_focus\">False</property><child><object class=\"GtkLabel"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"margin_left\">12</property><propert"
  "y name=\"margin_right\">12</property><property name=\"margin_top\">12</"
  "property><property name=\"margin_bottom\">12</property><property name=\""
  "label\" translatable=\"yes\">These applications are a part of the curre"
  "ntly-running session,\nand can be saved now or when you log out.\nChang"
  "es below will only take effect when the session is saved.</property><pr"
  "operty name=\"use_markup\">True</property><property name=\"xalign\">0</"
  "property></object></child></object><object class=\"XfceTitledDialog\" i"
  "d=\"xfce4_session_settings_dialog\"><property name=\"can_focus\">False<"
  "/property><property name=\"title\" translatable=\"yes\">Session and Sta"
  "rtup</property><property name=\"window_position\">center-on-parent</pro"
  "perty><property name=\"default_width\">600</property><property name=\"d"
  "efault_height\">500</property><property name=\"icon_name\">org.xfce.ses"
  "sion</property><property name=\"type_hint\">normal</property><child int"
  "ernal-child=\"vbox\"><object class=\"GtkBox\" id=\"dialog-vbox1\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"orientation\">vertical</property><property "
  "name=\"spacing\">2</property><child internal-child=\"action_area\"><obj"
  "ect class=\"GtkButtonBox\" id=\"dialog-action_area1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "child><object class=\"GtkButton\" id=\"button1\"><property name=\"label"
  "\" translatable=\"yes\">_Help</property><property name=\"use_action_app"
  "earance\">False</property><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><property name=\"receives_defa"
  "ult\">True</property><property name=\"image\">image7</property><propert"
  "y name=\"use_underline\">True</property></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">False</property><p"
  "roperty name=\"position\">0</property></packing></child><child><object "
  "class=\"GtkButton\" id=\"button2\"><property name=\"label\" translatabl"
  "e=\"yes\">_Close</property><property name=\"use_action_appearance\">Fal"
  "se</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">True</pr"
  "operty><property name=\"image\">image5</property><property name=\"use_u"
  "nderline\">True</property></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">False</property><property name=\""
  "position\">1</property></packing></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"pack_type\">end</property><property name=\"position\">1<"
  "/property></packing></child><child><object class=\"GtkNotebook\" id=\"p"
  "lug-child\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"border_width\">6</property>"
  "<child><object class=\"GtkBox\" id=\"vbox1\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"valign\">start</property><property name=\"border_width\">12</pro"
  "perty><property name=\"orientation\">vertical</property><property name="
  "\"spacing\">18</property><child><object class=\"GtkFrame\" id=\"frame1\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label_xalign\">0</property><property "
  "name=\"shadow_type\">none</property><child><object class=\"GtkAlignment"
  "\" id=\"alignment2\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"top_padding\">6</"
  "property><property name=\"left_padding\">12</property><child><object cl"
  "ass=\"GtkCheckButton\" id=\"chk_display_chooser\"><property name=\"labe"
  "l\" translatable=\"yes\">_Display chooser on login</property><property "
  "name=\"use_action_appearance\">False</property><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"receives_default\">False</property><property name=\"tooltip_tex"
  "t\" translatable=\"yes\">Display the session chooser every time Xfce st"
  "arts</property><property name=\"use_underline\">True</property><propert"
  "y name=\"xalign\">0.5</property><property name=\"draw_indicator\">True<"
  "/property></object></child></object></child><child type=\"label\"><obje"
  "ct class=\"GtkLabel\" id=\"label6\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"la"
  "bel\" translatable=\"yes\">&lt;b&gt;Session Chooser&lt;/b&gt;</property"
  "><property name=\"use_markup\">True</property></object></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">0</property></packing><"
  "/child><child><object class=\"GtkFrame\" id=\"frame2\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label_xalign\">0</property><property name=\"shadow_type"
  "\">none</property><child><object class=\"GtkAlignment\" id=\"alignment3"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"top_padding\">6</property><property"
  " name=\"left_padding\">12</property><child><object class=\"GtkBox\" id="
  "\"vbox2\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"orientation\">vertical</prop"
  "erty><property name=\"spacing\">6</property><child><object class=\"GtkC"
  "heckButton\" id=\"chk_session_autosave\"><property name=\"label\" trans"
  "latable=\"yes\">Automatically save session on logo_ut</property><proper"
  "ty name=\"use_action_appearance\">False</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">False</property><property name=\"tooltip_"
  "text\" translatable=\"yes\">Always save the session when logging out</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"xalign\">0.5</property><property name=\"draw_indicator\">True</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkCheckButton\" id=\"chk_logo"
  "ut_prompt\"><property name=\"label\" translatable=\"yes\">Pro_mpt on lo"
  "gout</property><property name=\"use_action_appearance\">False</property"
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">False</property><pr"
  "operty name=\"tooltip_text\" translatable=\"yes\">Prompt for confirmati"
  "on when logging out</property><property name=\"use_underline\">True</pr"
  "operty><property name=\"xalign\">0.5</property><property name=\"active\""
  ">True</property><property name=\"draw_indicator\">True</property></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child></object></child></object></child><child type=\"label\"><objec"
  "t class=\"GtkLabel\" id=\"label7\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lab"
  "el\" translatable=\"yes\">&lt;b&gt;Logout Settings&lt;/b&gt;</property>"
  "<property name=\"use_markup\">True</property></object></child></object>"
  "<packing><property name=\"expand\">True</property><property name=\"fill"
  "\">True</property><property name=\"position\">1</property></packing></c"
  "hild><child><object class=\"GtkFrame\" id=\"frame5\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"label_xalign\">0</property><property name=\"shadow_type\""
  ">none</property><child><object class=\"GtkAlignment\" id=\"alignment1\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"top_padding\">6</property><property n"
  "ame=\"left_padding\">12</property><child><object class=\"GtkBox\" id=\""
  "vbox6\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"orientation\">vertical</proper"
  "ty><property name=\"spacing\">6</property><child><object class=\"GtkChe"
  "ckButton\" id=\"chk_lock_screen\"><property name=\"label\" translatable"
  "=\"yes\">Lock screen be_fore sleep</property><property name=\"use_actio"
  "n_appearance\">False</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"receives"
  "_default\">False</property><property name=\"tooltip_text\" translatable"
  "=\"yes\">Run xflock4 before suspending or hibernating the system</prope"
  "rty><property name=\"use_underline\">True</property><property name=\"xa"
  "lign\">0</property><property name=\"draw_indicator\">True</property></o"
  "bject><packing><property name=\"expand\">False</property><property name"
  "=\"fill\">True</property><property name=\"position\">0</property></pack"
  "ing></child></object></child></object></child><child type=\"label\"><ob"
  "ject class=\"GtkLabel\" id=\"label25\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">&lt;b&gt;Shutdown&lt;/b&gt;</property><pro"
  "perty name=\"use_markup\">True</property></object></child></object><pac"
  "king><property name=\"expand\">True</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">2</property></packing></child"
  "></object></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"l"
  "abel1\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"label\" translatable=\"yes\">_"
  "General</property><property name=\"use_underline\">True</property></obj"
  "ect><packing><property name=\"tab_fill\">False</property></packing></ch"
  "ild><child><object class=\"GtkBox\" id=\"vbox8\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"border_width\">12</property><property name=\"orientation\">v"
  "ertical</property><child><object class=\"GtkInfoBar\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "child internal-child=\"action_area\"><object class=\"GtkButtonBox\"><pr"
  "operty name=\"can_focus\">False</property><property name=\"spacing\">6<"
  "/property><property name=\"layout_style\">end</property><child><object "
  "class=\"GtkButton\" id=\"btn_save_session\"><property name=\"label\" tr"
  "anslatable=\"yes\">Save Sess_ion</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"receives_default\">True</property><property name=\"valign\">center<"
  "/property><property name=\"image\">image2</property><property name=\"us"
  "e_underline\">True</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"pack_type\">end</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkMenuButton\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">True</property><property name=\"popov"
  "er\">session-info</property><child><object class=\"GtkImage\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"icon_name\">dialog-information-symbolic</proper"
  "ty></object></child><style><class name=\"circular\"/></style></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">True</property><property name=\"pack_type\">end</property><property "
  "name=\"position\">1</property><property name=\"non_homogeneous\">True</"
  "property></packing></child></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">False</property><property name="
  "\"position\">0</property></packing></child><child internal-child=\"cont"
  "ent_area\"><object class=\"GtkBox\"><property name=\"can_focus\">False<"
  "/property><child><object class=\"GtkLabel\" id=\"label_active_session\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">Currentl"
  "y active session: &lt;b&gt;Default&lt;/b&gt;</property><property name=\""
  "use_markup\">True</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">0</property></packing></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">False</property"
  "><property name=\"position\">0</property></packing></child><child><plac"
  "eholder/></child></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">1</property></packing></child><child><object class=\"GtkScrolledWindow"
  "\" id=\"scrolledwindow4\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><property name=\"shadow_type\""
  ">etched-in</property><child><object class=\"GtkTreeView\" id=\"treeview"
  "_clients\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><child internal-child=\"selection\"><object c"
  "lass=\"GtkTreeSelection\" id=\"treeview-selection2\"/></child></object>"
  "</child></object><packing><property name=\"expand\">True</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">2</prope"
  "rty></packing></child><child><object class=\"GtkBox\" id=\"hbox7\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"spacing\">6</property><child><object class"
  "=\"GtkBox\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><child><placeholder/></child><child><object"
  " class=\"GtkButton\" id=\"btn_quit_client\"><property name=\"label\" tr"
  "anslatable=\"yes\">_Quit Program</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"receives_default\">True</property><property name=\"image\">image3</"
  "property><property name=\"use_underline\">True</property></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">1</property></packing></child"
  "><style><class name=\"inline-toolbar\"/></style></object><packing><prop"
  "erty name=\"expand\">True</property><property name=\"fill\">True</prope"
  "rty><property name=\"pack_type\">end</property><property name=\"positio"
  "n\">3</property></packing></child></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">True</property><property"
  " name=\"position\">3</property></packing></child></object><packing><pro"
  "perty name=\"position\">1</property></packing></child><child type=\"tab"
  "\"><object class=\"GtkLabel\" id=\"label3\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"label\" translatable=\"yes\">Current Sessio_n</property><property"
  " name=\"use_underline\">True</property></object><packing><property name"
  "=\"position\">1</property><property name=\"tab_fill\">False</property><"
  "/packing></child><child><object class=\"GtkBox\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"border_width\">12</property><property name=\"orientation\">v"
  "ertical</property><child><object class=\"GtkBox\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"orientation\">vertical</property><child><object class=\"Gtk"
  "ScrolledWindow\" id=\"saved-sessions\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">True</property><property name=\""
  "shadow_type\">in</property><child><object class=\"GtkTreeView\" id=\"sa"
  "ved-sessions-list\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">True</property><child internal-child=\"selection\">"
  "<object class=\"GtkTreeSelection\"/></child></object></child></object><"
  "packing><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkBox\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><child><object class"
  "=\"GtkBox\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"orientation\">vertical</pr"
  "operty><child><object class=\"GtkButton\" id=\"btn_delete_session\"><pr"
  "operty name=\"label\" translatable=\"yes\">_Remove</property><property "
  "name=\"visible\">True</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"receives_default\">True</property><property name="
  "\"tooltip_text\" translatable=\"yes\">Delete the selected session</prop"
  "erty><property name=\"image\">image4</property><property name=\"use_und"
  "erline\">True</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">0</property></packing></child><child><object cl"
  "ass=\"GtkBox\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"orientation\">vertical<"
  "/property><child><object class=\"GtkButton\" id=\"btn_clear_sessions\">"
  "<property name=\"label\" translatable=\"yes\">Clear Save_d Sessions</pr"
  "operty><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"receives_default\">True</propert"
  "y><property name=\"halign\">end</property><property name=\"valign\">cen"
  "ter</property><property name=\"image\">image1</property><property name="
  "\"use_underline\">True</property><property name=\"always_show_image\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">0"
  "</property></packing></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">False</property><property name"
  "=\"pack_type\">end</property><property name=\"position\">1</property></"
  "packing></child><style><class name=\"inline-toolbar\"/></style></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">1</property></packing><"
  "/child></object><packing><property name=\"expand\">True</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">0</proper"
  "ty></packing></child></object><packing><property name=\"position\">3</p"
  "roperty></packing></child><child type=\"tab\"><object class=\"GtkLabel\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">Saved _S"
  "essions</property><property name=\"use_underline\">True</property></obj"
  "ect><packing><property name=\"position\">1</property><property name=\"t"
  "ab_fill\">False</property></packing></child><child><object class=\"GtkB"
  "ox\" id=\"vbox3\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"border_width\">12</p"
  "roperty><property name=\"orientation\">vertical</property><property nam"
  "e=\"spacing\">18</property><child><object class=\"GtkFrame\" id=\"frame"
  "3\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"label_xalign\">0</property><proper"
  "ty name=\"shadow_type\">none</property><child><object class=\"GtkAlignm"
  "ent\" id=\"alignment4\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"top_padding\">"
  "6</property><property name=\"left_padding\">12</property><child><object"
  " class=\"GtkBox\" id=\"vbox4\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"orienta"
  "tion\">vertical</property><property name=\"spacing\">6</property><child"
  "><object class=\"GtkCheckButton\" id=\"chk_compat_gnome\"><property nam"
  "e=\"label\" translatable=\"yes\">Launch GN_OME services on startup</pro"
  "perty><property name=\"use_action_appearance\">False</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">False</property><property na"
  "me=\"tooltip_text\" translatable=\"yes\">Start GNOME services, such as "
  "gnome-keyring</property><property name=\"use_underline\">True</property"
  "><property name=\"xalign\">0.5</property><property name=\"draw_indicato"
  "r\">True</property></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkCheckButton"
  "\" id=\"chk_compat_kde\"><property name=\"label\" translatable=\"yes\">"
  "Launch _KDE services on startup</property><property name=\"use_action_a"
  "ppearance\">False</property><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"receives_de"
  "fault\">False</property><property name=\"tooltip_text\" translatable=\""
  "yes\">Start KDE services, such as kdeinit</property><property name=\"us"
  "e_underline\">True</property><property name=\"xalign\">0.5</property><p"
  "roperty name=\"draw_indicator\">True</property></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">1</property></packing></child></object>"
  "</child></object></child><child type=\"label\"><object class=\"GtkLabel"
  "\" id=\"label8\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"label\" translatable="
  "\"yes\">&lt;b&gt;Compatibility&lt;/b&gt;</property><property name=\"use"
  "_markup\">True</property></object></child></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"position\">0</property></packing></child><child><object"
  " class=\"GtkFrame\" id=\"frame4\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l_xalign\">0</property><property name=\"shadow_type\">none</property><c"
  "hild><object class=\"GtkAlignment\" id=\"alignment5\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"top_padding\">6</property><property name=\"left_padding"
  "\">12</property><child><object class=\"GtkCheckButton\" id=\"chk_enable"
  "_tcp\"><property name=\"label\" translatable=\"yes\">Manage _remote app"
  "lications</property><property name=\"use_action_appearance\">False</pro"
  "perty><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">True</property><property name=\"receives_default\">False</propert"
  "y><property name=\"tooltip_text\" translatable=\"yes\">Manage remote ap"
  "plications over the network (this may be a security risk)</property><pr"
  "operty name=\"use_underline\">True</property><property name=\"xalign\">"
  "0.5</property><property name=\"draw_indicator\">True</property></object"
  "></child></object></child><child type=\"label\"><object class=\"GtkLabe"
  "l\" id=\"label9\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"label\" translatable"
  "=\"yes\">&lt;b&gt;Security&lt;/b&gt;</property><property name=\"use_mar"
  "kup\">True</property></object></child></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">1</property></packing></child></object><packing>"
  "<property name=\"position\">3</property></packing></child><child type=\""
  "tab\"><object class=\"GtkLabel\" id=\"label4\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"label\" translatable=\"yes\">Ad_vanced</property><property nam"
  "e=\"use_underline\">True</property></object><packing><property name=\"p"
  "osition\">3</property><property name=\"tab_fill\">False</property></pac"
  "king></child><child><placeholder/></child><child type=\"tab\"><placehol"
  "der/></child></object><packing><property name=\"expand\">True</property"
  "><property name=\"fill\">True</property><property name=\"position\">0</"
  "property></packing></child></object></child><action-widgets><action-wid"
  "get response=\"-11\">button1</action-widget><action-widget response=\"-"
  "7\">button2</action-widget></action-widgets></object><object class=\"Gt"
  "kDialog\" id=\"dialog_saving\"><property name=\"can_focus\">False</prop"
  "erty><property name=\"border_width\">5</property><property name=\"title"
  "\" translatable=\"yes\">Saving Session</property><property name=\"resiz"
  "able\">False</property><property name=\"window_position\">center-on-par"
  "ent</property><property name=\"destroy_with_parent\">True</property><pr"
  "operty name=\"icon_name\">xfce4-session</property><property name=\"type"
  "_hint\">dialog</property><property name=\"skip_taskbar_hint\">True</pro"
  "perty><property name=\"skip_pager_hint\">True</property><property name="
  "\"transient_for\">xfce4_session_settings_dialog</property><child><place"
  "holder/></child><child internal-child=\"vbox\"><object class=\"GtkBox\""
  " id=\"dialog-vbox2\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"orientation\">ver"
  "tical</property><property name=\"spacing\">2</property><child internal-"
  "child=\"action_area\"><object class=\"GtkButtonBox\" id=\"dialog-action"
  "_area2\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"layout_style\">end</property>"
  "<child><object class=\"GtkButton\" id=\"button3\"><property name=\"labe"
  "l\">_Close</property><property name=\"use_action_appearance\">False</pr"
  "operty><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"receives_default\">True</propert"
  "y><property name=\"image\">image8</property><property name=\"use_underl"
  "ine\">True</property></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">False</property><property name=\"posi"
  "tion\">0</property></packing></child></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"pack_type\">end</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkBox\" id=\"vbox5\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"border_width\">6</property><property name"
  "=\"orientation\">vertical</property><property name=\"spacing\">6</prope"
  "rty><child><object class=\"GtkBox\" id=\"hbox8\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"spacing\">12</property><child><object class=\"GtkImage\" id="
  "\"image6\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"icon_name\">dialog-informat"
  "ion</property><property name=\"icon_size\">6</property></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkLabel\" id=\"label10\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"label\" translatable=\"yes\">Your session is being saved.  If"
  " you do not wish to wait, you may close this window.</property><propert"
  "y name=\"wrap\">True</property><property name=\"xalign\">0</property></"
  "object><packing><property name=\"expand\">True</property><property name"
  "=\"fill\">True</property><property name=\"position\">1</property></pack"
  "ing></child></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">True</property><property name=\"position\">0</"
  "property></packing></child><child><object class=\"GtkProgressBar\" id=\""
  "progress_save_session\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">1</property></packing></child></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">1</property></packing></child><"
  "/object></child><action-widgets><action-widget response=\"0\">button3</"
  "action-widget></action-widgets></object></interface>"
};

static const unsigned xfce4_session_settings_ui_length = 28511u;

